### ISSUE TITLE
Add/Edit Cruise Form

### ISSUE THREAD

**Issue by JLee2021** [JCopeland-PIFSC/radfish-cruise-app#9]
**Section 1: Basic Cruise Information Section**
Story: As a user, I want to fill in or modify basic information about a cruise, such as the cruise name and vessel name, so that the cruise can be accurately documented.

Acceptance Criteria:
1. The form includes fields for the cruise name and vessel name.
2. A dropdown list allows users to select from a predefined list of vessels.

**Section 2: Schedule Section**
Story: As a user, I want to specify or edit the start and end dates of a cruise so that the schedule can be tracked.

Acceptance Criteria:
1. Date picker fields are available for start date and end date.
2. An option to mark the cruise as "Ongoing" hides the end date field if necessary.

**Section 3: Ports Section**
Story: As a user, I want to define the departure and return ports for the cruise so that the cruise's itinerary is clear.

Acceptance Criteria:
1. Dropdown lists allow users to select both departure and return ports.
2. The return port field is optional for ongoing cruises.

**Section 4: Satus Section**
Story: As a user, I want to set or change the cruise status to reflect its current state, so that the cruise’s lifecycle can be tracked.

Acceptance Criteria:
1. A dropdown list allows users to choose from statuses like Started, Ended, Submitted, Rejected, or Accepted.
2. A text area for comments enables users to add additional notes about the cruise's status or conditions.

**Section 5: Save, Cancel, and Delete Actions in Cruise Form**

Story: As a user, I want to be able to save, cancel, or delete changes made to a cruise so that I have control over cruise data management.
Acceptance Criteria:

1. A "Save" button lets users submit the form and save changes.
2. A "Cancel" button allows users to exit the form without saving changes.
3. A "Delete" button prompts a confirmation dialog before permanently deleting the cruise.

**Comment by JCopeland-PIFSC** [comment]
New Form:
- [ ] cruise name
- [ ] vessel name (drop-down)
- [ ] start date
- [ ] departure port
- [ ] cruise status
- [ ] Save button
